### ISSUE TITLE
Strip decimal from rates embed when bolded. 

### ISSUE THREAD

**Issue by travipross** [FM-17/poglink#27]
Currently the `rstrip()` command being used to remove trailing `.0` characters from the printed rates values fails to do so when certain values are marked as bolded (i.e. wrapped in `**`).

The trailing `.0` decimals should be stripped regardless of bolding.

**Comment by hocheukhei** [comment]
Maybe try using regular expressions?

Import the regular expressions module
`import re`

Replace the string
`re.sub("\.0+([\*]*)$","\g<1>",v)`

The code above will also work on multiple zeros such as .0000, if there is any other character the string is wrapped around simply add them in the square brackets [] , you will need the backslash if the character is a meta character

See:
https://www.w3schools.com/python/python_regex.asp

Hope this helps.
